project_id = "fkveoqzztgwdeayaqixv"

[functions.rss-feed]
verify_jwt = false

[functions.moderate-content]
verify_jwt = true

[functions.evaluate-user-role]
verify_jwt = false

[functions.track-presence]
verify_jwt = false

[functions.moderate-video]
verify_jwt = true

[functions.prohub-bot]
verify_jwt = false

[functions.auto-moderate-topics]
verify_jwt = false
